include $(FA_ENV_PRECOM)

MODULO=MtoMinFact

EXE=$(XPF_EXE)/

O=$(FA_LIB_PATH)/
H=$(FA_INC_PATH)/


FUENTE_PROC = $(PC)$(MODULO).pc
FUENTE_INTERMEDIO = $(C)$(MODULO).c
FUENTE_DEFINE = $(H)$(MODULO).h
OBJETO = $(O)$(MODULO).o

all:$(OBJETO) 

$(FUENTE_INTERMEDIO): $(FUENTE_PROC)
	$(PROC) $(FA_PROCFLAGS) HOLD_CURSOR=YES RELEASE_CURSOR=NO MAXOPENCURSORS=3 userid=$(USERPASS) iname=$(FUENTE_PROC) oname=$(FUENTE_INTERMEDIO)

$(OBJETO): $(FUENTE_INTERMEDIO) $(FUENTE_DEFINE)
	$(CC) $(CFLAGS) -c  $(FUENTE_INTERMEDIO) -o $(OBJETO)

clean: 
	-rm $(OBJETO) $(FUENTE_INTERMEDIO)

