DROP MATERIALIZED VIEW VM_FA_HISTDOCU_PRE;

DROP TABLE VM_FA_HISTDOCU_G;

DROP MATERIALIZED VIEW VM_FA_HISTCONC_G;

DROP MATERIALIZED VIEW VM_FA_HISTCONC_GDNC;

DROP MATERIALIZED VIEW VM_FA_AJUSTES_G;

DROP MATERIALIZED VIEW VM_FA_HISTDOCU_F;

DROP MATERIALIZED VIEW VM_FA_HISTCONC_F;

TRUNCATE TABLE SISCEL.FA_CAMBIA_LLAVE_TO;


UPDATE FA_CICLOS_PROCESADOS_TO
SET FECHA_TERMINO=SYSDATE, ESTADO='OK'
WHERE COD_CICLFACT=19010102;

COMMIT;
 
exit; 
 