DROP MATERIALIZED VIEW VM_AL_ARTICULOS; 

DROP MATERIALIZED VIEW VM_AL_CARGOS;

DROP MATERIALIZED VIEW VM_AL_PETIGUIAS_ABO;

DROP MATERIALIZED VIEW VM_FAD_CONCEVAL;

DROP MATERIALIZED VIEW VM_FAD_CONCAPLI;

DROP MATERIALIZED VIEW VM_FAD_DETPLANDESC;

DROP MATERIALIZED VIEW VM_FA_DETPASOCOBROS;

DROP MATERIALIZED VIEW VM_FA_NCPARCIAL;

DROP MATERIALIZED VIEW VM_FAD_CTLINFCONC;

DROP MATERIALIZED VIEW VM_FAT_PRESUPTEMP;

DROP MATERIALIZED VIEW VM_FA_PREFACTURA;

DROP MATERIALIZED VIEW VM_GA_ACTUASERV;

DROP MATERIALIZED VIEW VM_GA_AUTORIZA;

DROP MATERIALIZED VIEW VM_GA_CARGOS_RECHAZADOS;

DROP MATERIALIZED VIEW VM_GA_DET_PRELIQ;

DROP MATERIALIZED VIEW VM_GA_HSERVSUPLABO;

DROP MATERIALIZED VIEW VM_GA_SERVSUPLABO;

DROP MATERIALIZED VIEW VM_GE_CARGOS;

DROP MATERIALIZED VIEW VM_RE_FACTURA_DETALLE_TO;

DROP MATERIALIZED VIEW VM_SP_AVERIAS;

DROP MATERIALIZED VIEW VM_SP_AVERIAS_CARGOCTA;

DROP MATERIALIZED VIEW VM_TA_CONCEPFACT;

DROP MATERIALIZED VIEW VM_FA_PRESUPUESTO;

EXIT;

