UPDATE GA_INFACCEL 
SET IND_ACTUAC = 2
WHERE   COD_CLIENTE > 0
AND     NUM_ABONADO >= 0
AND     COD_CICLFACT =  &1
AND     IND_ACTUAC = 8
AND     FEC_BAJA < TO_DATE('04081999','DDMMYYYY');
COMMIT;
--
UPDATE GA_INFACBEEP
SET IND_ACTUAC = 2
WHERE   COD_CLIENTE > 0
AND     NUM_ABONADO >= 0
AND     COD_CICLFACT =  &1
AND     IND_ACTUAC = 8
AND     FEC_BAJA < TO_DATE('04081999','DDMMYYYY');
COMMIT;            
--
UPDATE GA_INFACCEL 
SET IND_ACTUAC = 3
WHERE   COD_CLIENTE > 0
AND     NUM_ABONADO >= 0
AND     COD_CICLFACT =  &1
AND     IND_ACTUAC = 9
AND     FEC_BAJA < TO_DATE('04081999','DDMMYYYY');
COMMIT;
--
UPDATE GA_INFACBEEP
SET IND_ACTUAC = 3
WHERE   COD_CLIENTE > 0
AND     NUM_ABONADO >= 0
AND     COD_CICLFACT =  &1
AND     IND_ACTUAC = 9
AND     FEC_BAJA < TO_DATE('04081999','DDMMYYYY');
COMMIT;
--
EXIT
/
