

EXECUTE FA_REASIG_COD_CONCEPT_FACT_PG.FA_PROC_GRAB_LOG(10000, 2, null, sysdate, sqlcode, 'Eliminacion de los conceptos de las tablas FA_FACTCOBR, FA_GRPSERCONC, FA_GRUPOCOB, FA_IMP_GRUPOTOT, FA_IMPCONCEPTOS, FA_CONCEPTOS'); 

EXECUTE FA_REASIG_COD_CONCEPT_FACT_PG.FA_DEL_CONCEPTOS_FACTURABLES(1000);

--NUEVA MODIFICACIÓN BERNARDO MORA 16-04-2007 INC 39529, SE REINSERTAN LOS CONCEPTOS DISPONIBILIZADOS 
--DESPUES DEL BORRADO APRA QUE LOS TOME EL MANTENEDOR DE CONCEPTOS EN FAMANTE
Insert into FA_CONCEPTOS (COD_CONCEPTO, COD_PRODUCTO, 
	   		DES_CONCEPTO, COD_TIPCONCE, COD_MODULO, 
			IND_ACTIVO, COD_MONEDA, COD_CONCORIG, 
			COD_TIPDESCU, NOM_USUARIO, FEC_ULTMOD, 
			COD_PRODSERVTFN, IND_RECURRENTE, COD_SUBCONCEPTO, 
			IND_TECNOLOGIA, DEF_TECNOLOGIA)
SELECT CODIGO_CONCEPTO AS COD_CONCEPTO, 1 AS COD_PRODUCTO, 
	   	'REUTILIZABLE' AS DES_CONCEPTO ,  4 AS COD_TIPCONCE, 
		'FA' AS COD_MODULO, 1 AS IND_ACTIVO, '001' AS COD_MONEDA, 
		 NULL AS COD_CONCORIG, '1' AS COD_TIPDESCU, USER AS NOM_USUARIO, 
	   	 SYSDATE AS FEC_ULTMOD, 1 AS COD_PRODSERVTFN, 0 AS IND_RECURRENTE, 
	    	'TC' AS COD_SUBCONCEPTO, 0 AS IND_TECNOLOGIA, 
	    	'NOTECNO' AS DEF_TECNOLOGIA
FROM FA_ENTRADA_TO  
WHERE CODIGO_CONCEPTO NOT IN (SELECT COD_CONCEPTO FROM FA_CONCEPTOS);
/
COMMIT;
/
--NUEVA MODIFICACIÓN BERNARDO MORA 17-04-2007 INC 39534, SE GUARDAN LOS CONCEPTOS QUE .
--SE REASIGNARON EN LA TABLA HISTORICA RESPALDO DE LA TABLA PIVOTE FA_ENTRADA_TO
INSERT INTO FA_HIST_ENTRADA_TO (CODIGO_CONCEPTO, CODIGO_DESTINO, DES_CONCEPTO)
SELECT A.CODIGO_CONCEPTO, A.CODIGO_DESTINO, A.DES_CONCEPTO
FROM FA_ENTRADA_TO A  
WHERE A.CODIGO_CONCEPTO NOT IN (SELECT CODIGO_CONCEPTO FROM FA_HIST_ENTRADA_TO);
/
COMMIT;
/
EXIT;


