/* Setea estados del procesamientos ciclico */
DECLARE
	nExisteCiclo NUMBER;
BEGIN

	SELECT COUNT(1) INTO nExisteCiclo
	FROM FA_CICLOS_PROCESADOS_TO WHERE COD_CICLFACT = &&1;
	
	IF nExisteCiclo>0 THEN
		UPDATE FA_CICLOS_PROCESADOS_TO
		SET ESTADO='NO_APLICA',
		    FECHA_INICIO=SYSDATE
		WHERE COD_CICLFACT=&&1;
	ELSE
		INSERT INTO FA_CICLOS_PROCESADOS_TO (COD_CICLFACT, ESTADO, FECHA_INICIO, FECHA_TERMINO, DURACION)
		VALUES (&&1, 'NO_APLICA',SYSDATE, SYSDATE, NULL);

	END IF;
	
	
END;
/

COMMIT;

EXIT;

