whenever sqlerror exit sql.sqlcode
whenever oserror  exit oscode

DELETE FROM SISCEL.FA_VALIDA_CODIGOS_TO;

/*-----------------VEA INDICE PARA LA TABLA FA_HISTDOCU A TRAVES DEL CODIGO DE CICLO----------*/
EXECUTE FA_REASIG_COD_CONCEPT_FACT_PG.FA_PROC_GRAB_LOG(1, 0, null, sysdate, sqlcode, 'Crea un indice en PreValidacion, por codigo de ciclo en la tabla FA_HISTDOCU para acortar tiempos de procesamiento'); 

CREATE TABLE VM_FA_HISTDOCU_NCRED AS
SELECT *
FROM FA_HISTDOCU A
WHERE FEC_EMISION < SYSDATE
  AND COD_TIPDOCUM = 25
  AND EXISTS ( SELECT 1
	    FROM FA_HISTCONC_19010102 B, FA_ENTRADA_TO C 
	   WHERE A.IND_ORDENTOTAL = B.IND_ORDENTOTAL
	     AND B.COD_CONCEPTO   = C.CODIGO_CONCEPTO);






/*crear el indice para notas de crédito!!!!!!!!!!!!!!!!!!!*/
CREATE INDEX IND_FA_HISTDOCU_NCRED_SECUREL ON VM_FA_HISTDOCU_NCRED(NUM_SECUREL, COD_TIPDOCUMREl,COD_VENDEDOR_AGENTEREL, LETRAREL,COD_CENTRREL) ;

/*--MODIFICACION BM SE AGREGO NUEVO INDICE COD_CICLFACT EN VISTA DE LA FA_HISTDOCU EN CREATABLA.SQL--*/
CREATE INDEX IND_COD_CICLFACT ON FA_HISTDOCU (COD_CICLFACT);


--DECLARE
--   bResultado Boolean;
--BEGIN
--	bResultado:=FA_REASIG_COD_CONCEPT_FACT_PG.FA_PREVAL_REASIG_COD();
--END;	
--/

EXIT;

